version: '2'
services:
  redis:
    container_name: recipes-demo-redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    container_name: recipes-demo-db
    image: "postgres:10.1"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
