spring:
  application:
    name: edge-service

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: /api
  routes:
    recipe-catalog:
      path: /recipe-catalog
      serviceId: recipe-catalog

